### ISSUE TITLE
Configuration view doesn't load correctly when called back to foreground

### ISSUE THREAD

**Issue by Explorare** [SagerNet/SagerNet#343]
### Describe the bug

The configuration view shows nothing when called back to foreground. Switch between other tabs like group or route and switch back fix the issue temporarily.

### To Reproduce
1. Cold start the app. The config view is rendered correctly.
2. Start a connection to keep the background service alive. Close the app to put it into background.
3. Open the app again to call it back to foreground. The config view shows nothing.
4. Switch between other view like `Route` or `Group` and switch back, the config view is rendered correctly again.

### Debug Information

[SagerNet -587222260.zip](https://github.com/SagerNet/SagerNet/files/7832372/SagerNet.-587222260.zip)

### Screenshots

![image](https://user-images.githubusercontent.com/5090766/148626380-4ce55fc2-c784-4ca4-aa2c-01d8e0bd4ca4.png)

### Smartphone (please complete the following information)

- SagerNet 0.7-beta02
- Kernel version: 3.10.84-perf-gd46863f
- Device: BlackBerry PRIV
- OS: Android 6.0.1

**Comment by nekohasekai** [comment]
Should be fixed on the letest version.

**Comment by Explorare** [comment]
Just tested v0.7-beta06 and the issue still exists. Maybe I'm the only one who have this issue. If so, don't waste time on it because the system version in my device is too outdated. The core function works just fine.
